//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veronika_Domjancic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oprema
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Oprema()
        {
            this.Zaduzenje = new HashSet<Zaduzenje>();
        }
    
        public int OpremaID { get; set; }
        public string Model { get; set; }
        public string SN { get; set; }
        public string Stanje { get; set; }
        public int TipID { get; set; }
    
        public virtual TipOpreme TipOpreme { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zaduzenje> Zaduzenje { get; set; }
    }
}
