//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veronika_Domjancic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zaduzenje
    {
        public int OpremaID { get; set; }
        public int ZaposlenikID { get; set; }
        public System.DateTime DatumZaduzivanja { get; set; }
        public Nullable<System.DateTime> DatumRazduzivanja { get; set; }
    
        public virtual Oprema Oprema { get; set; }
        public virtual Zaposlenik Zaposlenik { get; set; }
    }
}
